### ISSUE TITLE
Error: spawn EACCES during npm install

### ISSUE THREAD

**Issue by wmitsuda** [chrisa/node-dtrace-provider#104]
I'm getting this error on macos 10.12.6. Not sure what does it mean.

~/test  npm -v
5.4.1
 ~/test  node -v
v6.9.1
 ~/test  npm init -y

<lots-of-outputs>

 ~/test  npm install --save dtrace-provider

> dtrace-provider@0.8.5 install /Users/wmitsuda/test/node_modules/dtrace-provider
> node scripts/install.js

internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.<anonymous> (/Users/wmitsuda/test/node_modules/dtrace-provider/scripts/install.js:31:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtrace-provider@0.8.5 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.8.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wmitsuda/.npm/_logs/2017-09-12T21_03_11_166Z-debug.log

**Comment by wmitsuda** [comment]
Sorry, please ignore this issue. I tried the latest lts node version and it worked. It seems something specific to v6.9.1.
