### ISSUE TITLE
Error: The module '/Users/guojunbing23/gitresource/blong/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'

### ISSUE THREAD

**Issue by JackGuoFranklin** [chrisa/node-dtrace-provider#108]
Error: The module '/Users/guojunbing23/gitresource/blong/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:624:30) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guojunbing23/gitresource/blong/node_modules/hexo-log/lib/log.js:3:14)
    at Module._compile (module.js:624:30) code: 'MODULE_NOT_FOUND' }
(node:4244) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
怎么 解决，谢谢。

**Comment by melloc** [comment]
@JackGuoFranklin This is the error message that you'll get when you try to load node addons w/o first recompiling. You should be able to fix this by running `npm rebuild`, or by deleting your `node_modules` directory and running `npm install`.
