### ISSUE TITLE
Install fails on FreeBSD

### ISSUE THREAD

**Issue by mcavage** [chrisa/node-dtrace-provider#30]
Hey Chris-

I got this report from restify - I doubt node-dtrace will work on freebsd (afaik, usdt doesn't at all) - is that something hard to blacklist in your build script?

```
gmake: Entering directory `/root/test/node_modules/restify/node_modules/dtrace-provider/build'
  ACTION binding_gyp_libusdt_target_build_libusdt .
Building libusdt for x86_64
gmake[1]: Entering directory `/root/test/node_modules/restify/node_modules/dtrace-provider/libusdt'
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common   -c -o usdt.o usdt.c
In file included from usdt.c:5:
usdt_internal.h:5:24: error: sys/dtrace.h: No such file or directory
In file included from usdt.c:5:
usdt_internal.h:35: error: expected specifier-qualifier-list before 'dof_secidx_t'
usdt_internal.h:48: error: expected declaration specifiers or '...' before 'dof_secidx_t'
usdt_internal.h:53: error: expected specifier-qualifier-list before 'dof_secidx_t'
usdt_internal.h:65: error: expected declaration specifiers or '...' before 'dof_secidx_t'
usdt_internal.h:66: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'usdt_strtab_add'
usdt.c: In function 'usdt_provider_enable':
usdt.c:181: error: too many arguments to function 'usdt_strtab_init'
gmake[1]: *** [usdt.o] Error 1
gmake[1]: Leaving directory `/root/test/node_modules/restify/node_modules/dtrace-provider/libusdt'
gmake: *** [.] Error 2
gmake: Leaving directory `/root/test/node_modules/restify/node_modules/dtrace-provider/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:215:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System FreeBSD 9.0-RELEASE
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/test/node_modules/restify/node_modules/dtrace-provider
gyp ERR! node -v v0.8.4
gyp ERR! node-gyp -v v0.6.1
gyp ERR! not ok 
npm ERR! dtrace-provider@0.2.6 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
```

Thanks!
~Mark

**Comment by davepacheco** [comment]
@gabrielbiga Are you still seeing this issue with version 0.7.0?

**Comment by No9** [comment]
Hey @davepacheco to answer your last question:

On FreeBSD this module currently fails to load at runtime and the following is dumped to console
```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/home/anton/code/helloworld/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/home/anton/code/helloworld/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/home/anton/code/helloworld/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3) code: 'MODULE_NOT_FOUND' }
```
This is because the js wrapper expects the native lib to be built 
https://github.com/chrisa/node-dtrace-provider/blob/master/dtrace-provider.js#L25 
but the build is currently turned off 
https://github.com/chrisa/node-dtrace-provider/blob/master/compile.py#L3

These two pull requests reinstate FreeBSD support in this library:
https://github.com/chrisa/node-dtrace-provider/pull/85
https://github.com/chrisa/libusdt/pull/15 

Would be great to get these to land as I currently have to go and rebuild this out of band for libraries that have bunyan included.

**Comment by melloc** [comment]
Now that 15a2f1e is in, this issue can be closed.
