### ISSUE TITLE
Supress Error messages Regarding failure to load DtraceproviderBindings

### ISSUE THREAD

**Issue by mrludo** [chrisa/node-dtrace-provider#41]
On FreeBSD we get spammed by error messages at startup:

{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

I do not intend to use dtrace but some modules I am using require dtrace-provider (such as bunyan).

Could these error messages be supressed please ?

**Comment by stephank** [comment]
Offending line is here in dtrace-provider:
https://github.com/chrisa/node-dtrace-provider/blob/bba9fe9f9faf6005059c41f8af5ef3d39f3e6db2/dtrace-provider.js#L26

I guess, even if you don't intend to use it, dtrace-provider native code should build. This only happens if during `npm install` the native code fails to build.

The silly thing about dtrace-provider is that this is a warning, unlike pretty much every other NPM package where it's an error. It's very easy to look past the dtrace-provider install warning.

Build is failing since io.js 2.0.0. They should probably update NAN?

(I think, this issue was from Dec, and they did an update in Jan which should've unbroken it, but now it's broken again since this month because of the new io.js)

**Comment by lvegerano** [comment]
This is still an issue :cry:

**Comment by davepacheco** [comment]
@lvegerano dtrace-provider has been updated a few times since the last comment on this issue.  Which OS are you on?  Which versions of Node and dtrace-provider?  Did you see a build-time issue?

**Comment by lvegerano** [comment]
@davepacheco I'm using OSX 10.11.1 and the dtrace-provider version is the one tied to restify (0.6). I'm using node 4.2.2 with npm 3.4.1. And I did not see any build time issue. I looked into the dtrace repo and others have reported similar problems.

**Comment by davepacheco** [comment]
@lvegerano Are you referring to the issues in this issue?  As far as I can tell, this would require that you hit a build time problem (which you may not notice because the build won't fail for an optional dependency).  Otherwise dtrace-provider should be able to load the module it built.

I don't have a 10.11 machine available to debug this.  Could you provide the full repro steps (from the "git clone" of restify to the runtime error, including the build steps and all the output)?  Thanks!

**Comment by klik1301** [comment]
Hi, guys, I also had this issue

In my case problem was in Xcode, I didn't agree licence during install Xcode month before

 So I opened Xcode and clicked button "Agree" for licence

After that 
rm -rf node_modules
npm i

I hope it will help

**Comment by ShaunEgan** [comment]
Thanks @klik1301 - my Xcode needed to update. Thanks for the hint!

**Comment by caseyduquettesc** [comment]
I was using `pyenv` and had to run `pyenv rehash` and remove node_modules and then `yarn install` to fix the error in my case.

**Comment by NBR-hugh** [comment]
- My error message like below:

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Edgar/Repos/fintech-hackathon/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Edgar/Repos/fintech-hackathon/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Edgar/Repos/fintech-hackathon/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```
- And I update the OS X EI  to version 10.11.6 fix this error.

**Comment by melloc** [comment]
With `dtrace-provider@0.8.6`, these error messages will no longer be printed, and the fallback stub implementation will be used instead. If you do want to use the native binding, please try running the following:

```
$ NODE_DTRACE_PROVIDER_REQUIRE=hard npm install
```

I've added common compilation failure reasons to the README, so please take a look there after inspecting the output. If that doesn't help, then please open a new ticket.
