### ISSUE TITLE
npm install fails on Node v0.11.14

### ISSUE THREAD

**Issue by oncletom** [chrisa/node-dtrace-provider#54]
Here is the output of the `npm install` command:

```bash
$ V=true npm install

> dtrace-provider@0.3.0 install /Users/oncletom/workspace/node-dtrace-provider
> scripts/install.js

child_process: customFds option is deprecated, use stdio instead.
  LD_LIBRARY_PATH=/Users/oncletom/workspace/node-dtrace-provider/build/Release/lib.host:/Users/oncletom/workspace/node-dtrace-provider/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; sh libusdt-build.sh
Building libusdt for x86_64
make[1]: *** No rule to make target `clean'.  Stop.
make: *** [.] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/oncletom/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/oncletom/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/oncletom/workspace/node-dtrace-provider
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

And `npm ls`

```
$ npm ls
dtrace-provider@0.3.0 /Users/oncletom/workspace/node-dtrace-provider
├── nan@1.3.0
└─┬ tap@0.4.13
  ├── buffer-equal@0.0.1
  ├── deep-equal@0.0.0
  ├─┬ difflet@0.2.6
  │ ├── charm@0.1.2
  │ ├── deep-is@0.1.3
  │ └── traverse@0.6.6
  ├─┬ glob@3.2.11
  │ └─┬ minimatch@0.3.0
  │   ├── lru-cache@2.5.0
  │   └── sigmund@1.0.0
  ├── inherits@2.0.1
  ├─┬ mkdirp@0.5.0
  │ └── minimist@0.0.8
  ├─┬ nopt@2.2.1
  │ └── abbrev@1.0.5
  ├─┬ runforcover@0.0.2
  │ └─┬ bunker@0.1.2
  │   └─┬ burrito@0.2.12
  │     ├── traverse@0.5.2
  │     └── uglify-js@1.1.1
  ├── slide@1.1.6
  └── yamlish@0.0.6
```

**Comment by davepacheco** [comment]
This looks like what @chrisa suggested.  This module is known to work on 0.12.  If this problem recurs and it's not that, please reopen this issue or file a new one.
