### ISSUE TITLE
scripts/install.js hangs on OSX 10.10

### ISSUE THREAD

**Issue by ilyador** [chrisa/node-dtrace-provider#57]
```
$ npm install dtrace-provider
|
> dtrace-provider@0.3.1 install /Users/ilyo/dev/EndStream/server/node_modules/dtrace-provider
> scripts/install.js
```
And nothing happens for a long time.

**Comment by trentm** [comment]
What version of node? What platform?

Can you try running again with `V=1 npm install dtrace-provider` to get verbose output?

**Comment by indieisaconcept** [comment]
I'm having the same issue. I tried using `V=1 npm install dtrace-provider` as suggested above however it did not output anything.

**Comment by indieisaconcept** [comment]
Actually I was just able to get the following error.

```
> dtrace-provider@0.4.0 install /Users/.../app/node_modules/dtrace-provider
> node scripts/install.js


fs.js:555
  return binding.rename(pathModule._makeLong(oldPath),
                 ^
Error: ENOENT, no such file or directory '/Users/.../app/node_modules/node_modules/dtrace-provider/compile.py'
    at Object.fs.renameSync (fs.js:555:18)
    at Object.<anonymous> (/Users/.../app/node_modules/dtrace-provider/scripts/install.js:14:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by trentm** [comment]
@indieisaconcept *Is* that compile.py file there in your tree? What is the full path there, "/Users/.../app/node_modules/node_modules/dtrace-provider/compile.py"? Are there spaces or non-ascii chars involved there?

Does this work:

```
$ node
> var fs = require('fs');
> fs.existsSync('/Users/.../app/node_modules/node_modules/dtrace-provider/compile.py')  # using the actual full path
```

If you try to build your module using dtrace-provider a second time, does it work? (e.g. I've seen races in npm before, tho usually only when pulling directly from git repos).

**Comment by tklo** [comment]
I have the same issue in CircleCI job building a docker container:
```
> dtrace-provider@0.8.5 install /nectar-toolbox/node_modules/dtrace-provider
> node scripts/install.js
```

**Comment by melloc** [comment]
@tklo Which dependency of yours is pulling in `dtrace-provider@0.8.5`? I released 0.8.6 a week ago which reworked the build scripts, and should hopefully improve the build process.
