### ISSUE TITLE
Error: Cannot find module '/var/test/node_modules/bunyan/node_modules/dtrace-provider/scripts/install.js'

### ISSUE THREAD

**Issue by gularg** [chrisa/node-dtrace-provider#60]
node.js version:  0.10.36
OS:  CentOS6.6 x86_64

My rpm postinstall script executes the following command:

```
cd /var/test
npm install express redis amqp bunyan
```

When the script is run (when installing the rpm package), installing bunyan always fails:

```
> dtrace-provider@0.4.0 install /var/test/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js
 
|
module.js:340
    throw err;
          ^
Error: Cannot find module '/var/test/node_modules/bunyan/node_modules/dtrace-provider/scripts/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm WARN optional dep failed, continuing dtrace-provider@0.4.0
```

If I run "npm install express redis amqp bunyan" manually, everything works fine.

**Comment by marcellodesales** [comment]
Just got the same error today..

**Comment by davepacheco** [comment]
How reproducible is this for either of you?  If you run the command in a loop (and wipe the directory in between), does it happen again?  Especially when it's just failed, does it happen again?

**Comment by davepacheco** [comment]
@marcellodesales What OS and Node versions are you running?

**Comment by marcellodesales** [comment]
Hi @davepacheco 

I'm using RHEL7... I have 2 machines: one works and the other doesn't... Not sure I had installed binary, C++ packages... But I tried `yum install gcc*`and that did not solve the problem either...

Any suggestion?

```sh
[root@pppdc9prd9rj clients]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```

npm install
-----

```sh
[root@pppdc9prd9rj app]# git clone https://github.com/restify/clients.git
Cloning into 'clients'...
remote: Counting objects: 128, done.
remote: Total 128 (delta 0), reused 0 (delta 0), pack-reused 128
Receiving objects: 100% (128/128), 44.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (59/59), done.
[root@pppdc9prd9rj app]# cd clients/
[root@pppdc9prd9rj clients]# npm test

> restify-clients@1.1.1 test /app_local/clients
> make test

npm install
^C[root@pppdc9prd9rj clients]# make: *** [node_modules] Error 130
npm install

> dtrace-provider@0.6.0 install /app_local/clients/node_modules/dtrace-provider
> node scripts/install.js

|
module.js:340
    throw err;
          ^
Error: Cannot find module '/app_local/clients/node_modules/dtrace-provider/scripts/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
\
-
npm ERR! Linux 3.10.0-229.4.2.el7.x86_64
npm ERR! argv "node" "/bin/npm" "install"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! dtrace-provider@0.6.0 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the dtrace-provider@0.6.0 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app_local/clients/npm-debug.log
```

npm install --verbose
-----

The ending lines are... 

```sh
 info install core-js@1.2.6
npm info postinstall core-js@1.2.6
npm verb unlock done using /root/.npm/_locks/core-js-cba5e7741685dbe8.lock for /app_local/clients/node_modules/jscs/node_modules/babel-core/node_modules/core-js
npm verb about to build /app_local/clients/node_modules/jscs/node_modules/babel-core
npm info build /app_local/clients/node_modules/jscs/node_modules/babel-core
npm info linkStuff babel-core@5.8.34
npm verb linkBins babel-core@5.8.34
npm verb linkMans babel-core@5.8.34
npm verb rebuildBundles babel-core@5.8.34
npm verb rebuildBundles [ '.bin',
npm verb rebuildBundles   'babel-plugin-constant-folding',
npm verb rebuildBundles   'babel-plugin-dead-code-elimination',
npm verb rebuildBundles   'babel-plugin-eval',
npm verb rebuildBundles   'babel-plugin-inline-environment-variables',
npm verb rebuildBundles   'babel-plugin-jscript',
npm verb rebuildBundles   'babel-plugin-member-expression-literals',
npm verb rebuildBundles   'babel-plugin-property-literals',
npm verb rebuildBundles   'babel-plugin-proto-to-assign',
npm verb rebuildBundles   'babel-plugin-react-constant-elements',
npm verb rebuildBundles   'babel-plugin-react-display-name',
npm verb rebuildBundles   'babel-plugin-remove-console',
npm verb rebuildBundles   'babel-plugin-remove-debugger',
npm verb rebuildBundles   'babel-plugin-runtime',
npm verb rebuildBundles   'babel-plugin-undeclared-variables-check',
npm verb rebuildBundles   'babel-plugin-undefined-to-void',
npm verb rebuildBundles   'babylon',
npm verb rebuildBundles   'bluebird',
npm verb rebuildBundles   'convert-source-map',
npm verb rebuildBundles   'core-js',
npm verb rebuildBundles   'debug',
npm verb rebuildBundles   'detect-indent',
npm verb rebuildBundles   'esutils',
npm verb rebuildBundles   'fs-readdir-recursive',
npm verb rebuildBundles   'globals',
npm verb rebuildBundles   'home-or-tmp',
npm verb rebuildBundles   'is-integer',
npm verb rebuildBundles   'js-tokens',
npm verb rebuildBundles   'json5',
npm verb rebuildBundles   'line-numbers',
npm verb rebuildBundles   'minimatch',
npm verb rebuildBundles   'output-file-sync',
npm verb rebuildBundles   'path-exists',
npm verb rebuildBundles   'path-is-absolute',
npm verb rebuildBundles   'private',
npm verb rebuildBundles   'regenerator',
npm verb rebuildBundles   'regexpu',
npm verb rebuildBundles   'repeating',
npm verb rebuildBundles   'shebang-regex',
npm verb rebuildBundles   'slash',
npm verb rebuildBundles   'source-map',
npm verb rebuildBundles   'source-map-support',
npm verb rebuildBundles   'to-fast-properties',
npm verb rebuildBundles   'trim-right',
npm verb rebuildBundles   'try-resolve' ]
npm info install babel-core@5.8.34
npm info postinstall babel-core@5.8.34
npm verb unlock done using /root/.npm/_locks/babel-core-00f07e48e0063d8c.lock for /app_local/clients/node_modules/jscs/node_modules/babel-core
npm verb about to build /app_local/clients/node_modules/jscs
npm info build /app_local/clients/node_modules/jscs
npm info linkStuff jscs@2.6.0
npm verb linkBins jscs@2.6.0
npm verb link bins [ { jscs: './bin/jscs' },
npm verb link bins   '/app_local/clients/node_modules/.bin',
npm verb link bins   false ]
npm verb linkMans jscs@2.6.0
npm verb rebuildBundles jscs@2.6.0
npm verb rebuildBundles [ '.bin',
npm verb rebuildBundles   'babel-core',
npm verb rebuildBundles   'babel-jscs',
npm verb rebuildBundles   'chalk',
npm verb rebuildBundles   'cli-table',
npm verb rebuildBundles   'commander',
npm verb rebuildBundles   'escope',
npm verb rebuildBundles   'esprima',
npm verb rebuildBundles   'estraverse',
npm verb rebuildBundles   'exit',
npm verb rebuildBundles   'glob',
npm verb rebuildBundles   'htmlparser2',
npm verb rebuildBundles   'js-yaml',
npm verb rebuildBundles   'jscs-jsdoc',
npm verb rebuildBundles   'jscs-preset-wikimedia',
npm verb rebuildBundles   'jsonlint',
npm verb rebuildBundles   'minimatch',
npm verb rebuildBundles   'natural-compare',
npm verb rebuildBundles   'pathval',
npm verb rebuildBundles   'prompt',
npm verb rebuildBundles   'reserved-words',
npm verb rebuildBundles   'resolve',
npm verb rebuildBundles   'strip-bom',
npm verb rebuildBundles   'strip-json-comments',
npm verb rebuildBundles   'to-double-quotes',
npm verb rebuildBundles   'to-single-quotes',
npm verb rebuildBundles   'vow',
npm verb rebuildBundles   'vow-fs',
npm verb rebuildBundles   'xmlbuilder' ]
npm verb gentlyRm don't care about contents; nuking /app_local/clients/node_modules/.bin/jscs
npm info install jscs@2.6.0
npm info postinstall jscs@2.6.0
npm verb unlock done using /root/.npm/_locks/jscs-dce263d0a438748d.lock for /app_local/clients/node_modules/jscs
npm verb stack Error: dtrace-provider@0.6.0 install: `node scripts/install.js`
npm verb stack Exit status 8
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack     at EventEmitter.emit (events.js:98:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:98:17)
npm verb stack     at maybeClose (child_process.js:766:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm verb pkgid dtrace-provider@0.6.0
npm verb cwd /app_local/clients
npm ERR! Linux 3.10.0-229.4.2.el7.x86_64
npm ERR! argv "node" "/bin/npm" "install" "--verbose"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! dtrace-provider@0.6.0 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the dtrace-provider@0.6.0 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/dtrace-provider
npm info preuninstall dtrace-provider@0.6.0
npm info uninstall dtrace-provider@0.6.0
npm verb unbuild rmStuff dtrace-provider@0.6.0 from /app_local/clients/node_modules
npm info postuninstall dtrace-provider@0.6.0
npm verb gentlyRm don't care about contents; nuking /app_local/clients/node_modules/dtrace-provider

npm ERR! Please include the following file with any support request:
npm ERR!     /app_local/clients/npm-debug.log
```

**Comment by marcellodesales** [comment]
@davepacheco Here's the full logs https://gist.github.com/marcellodesales/844fc5f4412536e5abe8

**Comment by davepacheco** [comment]
The error message says that the script exited with status code 8.  In Node _after_ 0.10 (i.e., 0.12 and later), that's documented to be unused.  The documentation does say that some previous versions used it to denote that an uncaught exception was thrown.  It would be very strange for this file to have thrown an exception on Linux, because it bails out on line 6 without having done almost anything -- not even a require.

I tried this on SmartOS joyent_20150818T191104Z with node v0.10.40 and the bundled npm 1.4.28.  I also tried on the same system with node v0.10.40 and a locally-installed npm 2.14.12.  Both work reliably.  I also tried on OS X 10.8.5 with Node v0.10.28 and a locally-installed npm 2.14.12, and that worked.  I've no doubt that there's an issue here, but I think we're going to need your help to debug it.  It will probably help to isolate dtrace-provider (and ignore the restify-clients) piece.

**Comment by davepacheco** [comment]
@marcellodesales I misread the error message and focused on the "exit status 8" instead of the previous message that it could not find the script at all.  I noticed that you CTRL-C'd the initial "npm test".  Is this reproducible if you _don't_ CTRL-C the initial "npm test"?  It's possible you have a half-installed module there.  You could test this by doing a complete "npm install" in a separate directory tree, and then using "diff -r" to see how the directory trees differ.

**Comment by marcellodesales** [comment]
@davepacheco I did perform the full install multiple times in the machines... I will get back to review the installations after I finish developing the modules :( Haven't had time to do so :(

**Comment by marcellodesales** [comment]
@davepacheco I started getting this again... This doesn't fail on Ubuntu, but fails on RHEL 7... Not sure what's going on here... Same problem, npm install but this time it couldn't install dtrace.

```sh
e_modules/source-map
npm info linkStuff nan@2.1.0
npm info linkStuff source-map@0.2.0
npm info build /jenkins-home/var-lib-jenkins/jobs/BUILD-ISP-isp/branches/develop/workspace/node_modules/sp-logging/node_modules/bunyan/node_modules/dtrace-provider
npm info postinstall source-map@0.2.0
npm info postinstall mkdirp@0.3.0
npm info build /jenkins-home/var-lib-jenkins/jobs/BUILD-ISP-isp/branches/develop/workspace/node_modules/sp-quality/node_modules/mocha/node_modules/jade
npm info linkStuff dtrace-provider@0.6.0
npm info preinstall lodash@2.4.2
npm info linkStuff jade@0.26.3
npm info install dtrace-provider@0.6.0

> dtrace-provider@0.6.0 install /jenkins-home/var-lib-jenkins/jobs/BUILD-ISP-isp/branches/develop/workspace/node_modules/sp-logging/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

/
module.js:340
    throw err;
          ^
Error: Cannot find module '/jenkins-home/var-lib-jenkins/jobs/BUILD-ISP-isp/branches/develop/workspace/node_modules/sp-logging/node_modules/bunyan/node_modules/dtrace-provider/scripts/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm info build /jenkins-home/var-lib-jenkins/jobs/BUILD-ISP-isp/branches/develop/workspace/node_modules/sp-quality/node_modules/gulp-jshint/node_modules/rcloader/node_modules/rcfinder/node_modules/lodash
npm info install jade@0.26.3
```

**Comment by davepacheco** [comment]
I think we're back with what I said before: I've no doubt that there's an issue here, but I'm not seeing it directly and there's not enough postmortem information here for me to even guess at what's wrong, so I think we're going to need your help to debug it. (And I still think it will help to isolate dtrace-provider and ignore the restify-clients piece.)

**Comment by marcellodesales** [comment]
@davepacheco Sounds good... Here's the attempt to install dtrace by itself... I also upgraded Nodejs to the latest 4.2.3...

* What are the dependencies of dtrace?
* Do I need to install C++ compiler? Anything I depend on?
* Might not work on RHEL7
* It does work on Ubuntu

OS Version
----

```sh
[root@pppdc9prda9g Ops-Alert-Service]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)

[root@pppdc9prda9g Ops-Alert-Service]# uname -ra
Linux pppdc9prda9g 3.10.0-229.4.2.el7.x86_64 #1 SMP Fri Apr 24 15:26:38 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

npm version
-----

```js
[root@pppdc9prda9g Ops-Alert-Service]# npm version
npm info it worked if it ends with ok
npm info using npm@2.14.7
npm info using node@v4.2.3
{ 'ops-alert': '0.1.0',
  npm: '2.14.7',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '50.1.2',
  modules: '46',
  node: '4.2.3',
  openssl: '1.0.2e',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
npm info ok
```

Attempt to install with Node 4.2.3
------

It fails with a non-existent file `Error: Cannot find module '/app_local/Ops-Alert-Service/node_modules/dtrace-provider/scripts/install.js'`

```js
[root@pppdc9prda9g Ops-Alert-Service]# npm install dtrace-provider@0.6.0
npm info it worked if it ends with ok
npm info using npm@2.14.7
npm info using node@v4.2.3
npm WARN package.json ops-alert@0.1.0 license should be a valid SPDX license expression
npm info package.json model@6.0.1 No license field.
npm info package.json sp-server-restify-swagger@0.1.0 license should be a valid SPDX license expression
npm info attempt registry request try #1 at 5:33:18 AM
npm http request GET http://sds-repo-int.qdc.intuit.com:8082/nexus/content/groups/npm-all/dtrace-provider
npm http 200 http://sds-repo-int.qdc.intuit.com:8082/nexus/content/groups/npm-all/dtrace-provider
npm info retry fetch attempt 1 at 5:33:18 AM
npm info attempt registry request try #1 at 5:33:18 AM
npm http fetch GET http://sds-repo-dev.qdc.intuit.com:8082/nexus/content/groups/npm-all/dtrace-provider/-/dtrace-provider-0.6.0.tgz
npm http fetch 200 http://sds-repo-dev.qdc.intuit.com:8082/nexus/content/groups/npm-all/dtrace-provider/-/dtrace-provider-0.6.0.tgz
npm info install dtrace-provider@0.6.0 into /app_local/Ops-Alert-Service
npm info installOne dtrace-provider@0.6.0
npm info preinstall dtrace-provider@0.6.0
npm info attempt registry request try #1 at 5:33:18 AM
npm http request GET http://sds-repo-int.qdc.intuit.com:8082/nexus/content/groups/npm-all/nan
npm http 200 http://sds-repo-int.qdc.intuit.com:8082/nexus/content/groups/npm-all/nan
npm info install nan@2.1.0 into /app_local/Ops-Alert-Service/node_modules/dtrace-provider
npm info installOne nan@2.1.0
npm info preinstall nan@2.1.0
npm info build /app_local/Ops-Alert-Service/node_modules/dtrace-provider/node_modules/nan
npm info linkStuff nan@2.1.0
npm info install nan@2.1.0
npm info postinstall nan@2.1.0
npm info build /app_local/Ops-Alert-Service/node_modules/dtrace-provider
npm info linkStuff dtrace-provider@0.6.0
npm info install dtrace-provider@0.6.0

> dtrace-provider@0.6.0 install /app_local/Ops-Alert-Service/node_modules/dtrace-provider
> node scripts/install.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/app_local/Ops-Alert-Service/node_modules/dtrace-provider/scripts/install.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
npm info dtrace-provider@0.6.0 Failed to exec install script
npm ERR! Linux 3.10.0-229.4.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "dtrace-provider@0.6.0"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! dtrace-provider@0.6.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.6.0 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.
npm info preuninstall dtrace-provider@0.6.0
npm info uninstall dtrace-provider@0.6.0
npm info postuninstall dtrace-provider@0.6.0

npm ERR! Please include the following file with any support request:
npm ERR!     /app_local/Ops-Alert-Service/npm-debug.log
```

**Comment by marcellodesales** [comment]
I can clone and install the module without a problem...

Installing from git works
---- 
```js
[root@pppdc9prda9g Ops-Alert-Service]# cd ..
[root@pppdc9prda9g app]# git clone https://github.com/chrisa/node-dtrace-provider
Cloning into 'node-dtrace-provider'...
remote: Counting objects: 530, done.
remote: Total 530 (delta 0), reused 0 (delta 0), pack-reused 530
Receiving objects: 100% (530/530), 109.70 KiB | 173.00 KiB/s, done.
Resolving deltas: 100% (292/292), done.
[root@pppdc9prda9g app]# cd node-dtrace-provider/
```

```js
[root@pppdc9prda9g node-dtrace-provider]# npm install
npm WARN package.json dtrace-provider@0.6.0 No license field.
npm WARN deprecated tap-consumer@0.0.1: This module is not supported. Please use 'tap' instead.
npm WARN installMany tap-consumer was bundled with tap@0.2.6, but bundled package wasn't found in unpacked tree
npm WARN deprecated tap-results@0.0.2: This module is not supported. Please use 'tap' instead.
npm WARN cannot run in wd dtrace-provider@0.6.0 node scripts/install.js (wd=/app_local/node-dtrace-provider)
nan@2.1.0 node_modules/nan

tap@0.2.6 node_modules/tap
├── deep-equal@0.0.0
├── buffer-equal@0.0.1
├── slide@1.1.6
├── mkdirp@0.3.5
├── tap-consumer@0.0.1 (tap-results@0.0.2)
├── nopt@2.2.1 (abbrev@1.0.7)
├── difflet@0.2.6 (deep-is@0.1.3, charm@0.1.2, traverse@0.6.6)
└── runforcover@0.0.2 (bunker@0.1.2)
[root@pppdc9prda9g node-dtrace-provider]# cd -
/app
```

**Comment by marcellodesales** [comment]
I currently have 3 modules using dtrace-provider:

Could you please let me know if there's  a way to bypass the installation? I cannot find the reason... 

```js
mdesales@ubuntu [12/09/2015 22:10:56] ~/dev/github-intuit/servicesplatform-nodejs/sp-reference-restify (develop) $ npm ls dtrace-provider
npm info it worked if it ends with ok
npm info using npm@2.14.7
npm info using node@v0.10.40
sp-reference-restify@1.0.0 /home/mdesales/dev/github-intuit/servicesplatform-nodejs/sp-reference-restify

├─┬ restify@4.0.3
│ └── dtrace-provider@0.6.0 
https://github.com/restify/node-restify/blob/5.x/package.json#L84

 |   └─┬ bunyan@1.5.1
            └── dtrace-provider@0.6.0 
https://github.com/trentm/node-bunyan/blob/master/package.json#L22

└─┬ restify-clients@1.1.0
       └── dtrace-provider@0.6.0 
https://github.com/restify/clients/blob/master/package.json#L60
```

**Comment by marcellodesales** [comment]
Solution
----

We were using the `root` user... That caused the issue... With a regular user performing `npm install`, everything worked as expected!

thanks guys!

**Comment by davepacheco** [comment]
Glad to hear it's resolved, @marcellodesales!

@simonxu, are you still seeing this issue with the current version of node-dtrace-provider?

**Comment by marcellodesales** [comment]
@davepacheco Thank you! Yeah, the guys from @thorsten from @nodesource was here and they figured that out...
