### ISSUE TITLE
Install fails on io.js 2.0.1 and 2.1.0

### ISSUE THREAD

**Issue by toddself** [chrisa/node-dtrace-provider#64]
Same error on both:

```
../node_modules/nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
```

Here's the full stack.  I'm using v2.1.0 installed via nvm and 2.0.1 built and installed with `./configure --/opt/iojs && make && make install`

```
↳ V=1 npm i dtrace-provider
npm WARN package.json @scriptollc/deploybot-agent@1.0.0 No README data
npm WARN package.json @scriptollc/deploybot-agent@1.0.0 license should be a valid SPDX license expression
npm http request GET https://registry.npmjs.org/dtrace-provider
npm http 304 https://registry.npmjs.org/dtrace-provider
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> dtrace-provider@0.4.0 install /Users/todd/src/deploybot-agent/node_modules/dtrace-provider
> node scripts/install.js

  LD_LIBRARY_PATH=/Users/todd/src/deploybot-agent/node_modules/dtrace-provider/build/Release/lib.host:/Users/todd/src/deploybot-agent/node_modules/dtrace-provider/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; sh libusdt-build.sh
Building libusdt for x86_64
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -Wall -arch x86_64   -c -o usdt.o usdt.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -Wall -arch x86_64   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o
ranlib libusdt.a
  touch Release/obj.target/libusdt.stamp
  c++ '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/todd/.node-gyp/2.1.0/src -I/Users/todd/.node-gyp/2.1.0/deps/uv/include -I/Users/todd/.node-gyp/2.1.0/deps/v8/include -I../libusdt -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/DTraceProviderBindings/dtrace_provider.o.d.raw  -c -o Release/obj.target/DTraceProviderBindings/dtrace_provider.o ../dtrace_provider.cc
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:181:
../node_modules/nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/todd/.node-gyp/2.1.0/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/todd/src/nvm/versions/io.js/v2.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/todd/src/nvm/versions/io.js/v2.1.0/bin/iojs" "/Users/todd/src/nvm/versions/io.js/v2.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/todd/src/deploybot-agent/node_modules/dtrace-provider
gyp ERR! node -v v2.1.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
dtrace-provider@0.4.0 node_modules/dtrace-provider
└── nan@1.5.3
```

**Comment by davepacheco** [comment]
Please reopen if this is not a dup of #61.

**Comment by davepacheco** [comment]
As I mentioned, I think this was resolved a while ago.
